apiVersion: v1
kind: Service
metadata:
  name: {{ include "ollama.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 11434
      protocol: TCP
  selector:
    {{- include "ollama.selectorLabels" . | nindent 4 }}