replicaCount: 1

namespace: default

image:
  repository: yuyatinnefeld/deepseek-ollama
  pullPolicy: IfNotPresent
  tag: "latest"

containerName: ollama

service:
  type: NodePort
  port: 11434

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /root/.ollama